# Generated by Django 5.2.9 on 2026-05-15 06:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0042_add_number_of_licence_to_dealer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripOpenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(db_index=True, max_length=30)),
                ('palmtec_id', models.CharField(db_index=True, max_length=20)),
                ('route_code', models.CharField(blank=True, max_length=50, null=True)),
                ('up_down_trip', models.CharField(blank=True, choices=[('Up', 'Up'), ('Down', 'Down')], max_length=4, null=True)),
                ('trip_no', models.IntegerField()),
                ('bus_no', models.CharField(blank=True, max_length=30, null=True)),
                ('driver', models.CharField(blank=True, max_length=50, null=True)),
                ('conductor', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('battery_percentage', models.IntegerField(blank=True, null=True)),
                ('total_record', models.IntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_payload', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trip_open_data',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.AlterModelOptions(
            name='tripclosedata',
            options={'ordering': ['-start_datetime']},
        ),
        migrations.RenameIndex(
            model_name='etmdevice',
            new_name='etm_device_company_7b856c_idx',
            old_name='etm_dev_company_alloc_idx',
        ),
        migrations.RenameIndex(
            model_name='etmdevice',
            new_name='etm_device_allocat_3f20eb_idx',
            old_name='etm_dev_alloc_status_idx',
        ),
        migrations.RemoveField(
            model_name='transactiondata',
            name='request_type',
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='battery_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='bqr_merchant_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='bus_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='checksum',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='conductor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='driver',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='full_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='half_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='ladies_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='luggage_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='phy_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='route_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='TicketAppB.route'),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='schedule',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='senior_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='st_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='total_record',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='trip_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='trip_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='unique_code',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='up_down_trip',
            field=models.CharField(blank=True, choices=[('Up', 'Up'), ('Down', 'Down')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tripclosedata',
            name='checksum',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tripclosedata',
            name='conductor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tripclosedata',
            name='driver',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tripclosedata',
            name='raw_payload',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripclosedata',
            name='total_km',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tripclosedata',
            name='total_record',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripclosedata',
            name='unique_code',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rawdatalog',
            name='source',
            field=models.CharField(choices=[('transaction', 'Transaction'), ('trip_open', 'Trip Open'), ('trip_close', 'Trip Close'), ('schedule_open', 'Schedule Open'), ('schedule_close', 'Schedule Close')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='refund_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='ticket_status',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card')], default='Cash', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='ticket_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='warrant_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='adjust_collection',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='company_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='TicketAppB.company'),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='depot_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_closes', to='TicketAppB.depot'),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='end_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='end_ticket_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='expense_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='full_collection',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='full_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='half_collection',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='half_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='ladies_collection',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='ladies_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='luggage_collection',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='luggage_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='palmtec_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='pass_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='physical_collection',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='physical_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='route_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='schedule',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='senior_collection',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='senior_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='st1_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='st_collection',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='start_datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='start_ticket_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='total_cash_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='total_cash_tickets',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='total_collection',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='total_tickets',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='trip_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='up_down_trip',
            field=models.CharField(blank=True, choices=[('Up', 'Up'), ('Down', 'Down')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='upi_ticket_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='tripclosedata',
            name='upi_ticket_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='transactiondata',
            index=models.Index(fields=['unique_code'], name='transaction_unique__3e31ff_idx'),
        ),
        migrations.AddIndex(
            model_name='transactiondata',
            index=models.Index(fields=['ticket_date'], name='transaction_ticket__4d3d14_idx'),
        ),
        migrations.AddIndex(
            model_name='tripclosedata',
            index=models.Index(fields=['unique_code'], name='trip_close__unique__bbf484_idx'),
        ),
        migrations.AddField(
            model_name='tripopendata',
            name='company_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_opens', to='TicketAppB.company'),
        ),
        migrations.AddField(
            model_name='tripopendata',
            name='depot_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_opens', to='TicketAppB.depot'),
        ),
        migrations.AddIndex(
            model_name='tripopendata',
            index=models.Index(fields=['palmtec_id', 'start_datetime'], name='trip_open_d_palmtec_3bf009_idx'),
        ),
        migrations.AddIndex(
            model_name='tripopendata',
            index=models.Index(fields=['company_code'], name='trip_open_d_company_492c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='tripopendata',
            index=models.Index(fields=['start_date'], name='trip_open_d_start_d_bc0d03_idx'),
        ),
        migrations.AddIndex(
            model_name='tripopendata',
            index=models.Index(fields=['unique_code'], name='trip_open_d_unique__293cd9_idx'),
        ),
        migrations.AddConstraint(
            model_name='tripopendata',
            constraint=models.UniqueConstraint(fields=('palmtec_id', 'trip_no', 'start_date', 'start_time'), name='uniq_device_trip_open'),
        ),
    ]
