# Generated by Django 5.2.9 on 2026-05-15 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0043_tripopendata_alter_tripclosedata_options_and_more'),
    ]

    operations = [
        # These indexes were never created in DB — skip SQL, update state only
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='transactiondata',
                    name='transaction_depot_c_ec24c5_idx',
                ),
                migrations.RemoveIndex(
                    model_name='tripclosedata',
                    name='trip_close__route_c_64c498_idx',
                ),
                migrations.RemoveIndex(
                    model_name='tripclosedata',
                    name='trip_close__depot_c_2464aa_idx',
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='transactiondata',
            name='depot_code',
        ),
        migrations.RemoveField(
            model_name='tripclosedata',
            name='depot_code',
        ),
        migrations.RemoveField(
            model_name='tripclosedata',
            name='route_code',
        ),
        migrations.RemoveField(
            model_name='tripopendata',
            name='depot_code',
        ),
        migrations.RemoveField(
            model_name='tripopendata',
            name='route_code',
        ),
        migrations.AddField(
            model_name='tripclosedata',
            name='route_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_closes', to='TicketAppB.route'),
        ),
        migrations.AddField(
            model_name='tripopendata',
            name='route_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_opens', to='TicketAppB.route'),
        ),
        migrations.AddIndex(
            model_name='tripclosedata',
            index=models.Index(fields=['route_id', 'start_datetime'], name='trip_close__route_i_80d7e4_idx'),
        ),
    ]
