# Generated by Django 5.2.9 on 2026-05-18 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0045_add_schedule_open_close_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondata',
            name='from_stage_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_transactions', to='TicketAppB.routestage'),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='to_stage_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_transactions', to='TicketAppB.routestage'),
        ),
    ]
