# Generated by Django 5.2.9 on 2026-05-18 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0047_add_district_to_company_and_dealer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdometerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('palmtec_id', models.CharField(db_index=True, max_length=20)),
                ('schedule_no', models.IntegerField(db_index=True)),
                ('trip_no', models.IntegerField(db_index=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('driver', models.CharField(blank=True, max_length=50, null=True)),
                ('bus_no', models.CharField(blank=True, max_length=30, null=True)),
                ('start_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('end_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_read_flag', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('api', 'API'), ('dat', 'DAT Upload')], max_length=3)),
                ('checksum', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_payload', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odometer_records', to='TicketAppB.vehicletype')),
                ('company_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='odometer_records', to='TicketAppB.company')),
                ('driver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odometer_records', to='TicketAppB.employee')),
            ],
            options={
                'db_table': 'odometer_data',
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['palmtec_id', 'start_datetime'], name='odometer_da_palmtec_b24e2d_idx'), models.Index(fields=['company_code', 'start_date'], name='odometer_da_company_12b062_idx'), models.Index(fields=['company_code'], name='odometer_da_company_da1de1_idx'), models.Index(fields=['start_date'], name='odometer_da_start_d_5d977f_idx'), models.Index(fields=['unique_code'], name='odometer_da_unique__2509a1_idx'), models.Index(fields=['schedule_no', 'trip_no'], name='odometer_da_schedul_9d4c92_idx')],
                'constraints': [models.UniqueConstraint(fields=('palmtec_id', 'company_code', 'schedule_no', 'trip_no', 'start_datetime'), name='uniq_device_company_odometer')],
            },
        ),
    ]
