# Generated by Django 5.2.9 on 2026-05-18 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0048_add_odometer_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odometerdata',
            name='start_read_flag',
        ),
        migrations.AddField(
            model_name='odometerdata',
            name='conductor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odometerdata',
            name='conductor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_odometer_records', to='TicketAppB.employee'),
        ),
        migrations.AddField(
            model_name='odometerdata',
            name='error_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
