# Generated by Django 5.2.9 on 2026-05-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0049_add_conductor_error_reason_odometer'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scheduleclosedata',
            name='uniq_device_schedule_close',
        ),
        migrations.RemoveConstraint(
            model_name='scheduleopendata',
            name='uniq_device_schedule_open',
        ),
        migrations.RemoveConstraint(
            model_name='transactiondata',
            name='uniq_device_trip_ticket_datetime',
        ),
        migrations.RemoveConstraint(
            model_name='tripopendata',
            name='uniq_device_trip_open',
        ),
        migrations.AlterUniqueTogether(
            name='tripclosedata',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='scheduleclosedata',
            constraint=models.UniqueConstraint(fields=('palmtec_id', 'company_code', 'schedule_no', 'end_datetime'), name='uniq_device_schedule_close'),
        ),
        migrations.AddConstraint(
            model_name='scheduleopendata',
            constraint=models.UniqueConstraint(fields=('palmtec_id', 'company_code', 'schedule_no', 'start_date', 'start_time'), name='uniq_device_schedule_open'),
        ),
        migrations.AddConstraint(
            model_name='transactiondata',
            constraint=models.UniqueConstraint(fields=('palmtec_id', 'company_code', 'trip_number', 'ticket_number', 'ticket_date', 'ticket_time'), name='uniq_device_trip_ticket_datetime'),
        ),
        migrations.AddConstraint(
            model_name='tripclosedata',
            constraint=models.UniqueConstraint(fields=('palmtec_id', 'company_code', 'schedule', 'trip_no', 'start_datetime'), name='uniq_device_trip_close'),
        ),
        migrations.AddConstraint(
            model_name='tripopendata',
            constraint=models.UniqueConstraint(fields=('palmtec_id', 'company_code', 'trip_no', 'start_date', 'start_time'), name='uniq_device_trip_open'),
        ),
    ]
