# Generated by Django 5.2.9 on 2026-05-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0050_add_company_code_to_unique_constraints'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scheduleopendata',
            name='schedule_op_route_i_640aeb_idx',
        ),
        migrations.RemoveField(
            model_name='scheduleopendata',
            name='route_id',
        ),
    ]
