# Generated by Django 5.2.9 on 2026-05-19 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0051_remove_route_id_from_schedule_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('palmtec_id', models.CharField(db_index=True, max_length=20)),
                ('schedule_no', models.IntegerField(db_index=True)),
                ('trip_no', models.IntegerField(db_index=True)),
                ('expense_date', models.DateField(blank=True, null=True)),
                ('expense_time', models.TimeField(blank=True, null=True)),
                ('expense_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('driver', models.CharField(blank=True, max_length=50, null=True)),
                ('bus_no', models.CharField(blank=True, max_length=30, null=True)),
                ('expense_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diesel_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expense_type', models.IntegerField(blank=True, null=True)),
                ('error_reason', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('api', 'API'), ('dat', 'DAT Upload')], max_length=3)),
                ('checksum', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_payload', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_records', to='TicketAppB.vehicletype')),
                ('company_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_records', to='TicketAppB.company')),
                ('driver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_records', to='TicketAppB.employee')),
            ],
            options={
                'db_table': 'expense_data',
                'ordering': ['-expense_datetime'],
                'indexes': [models.Index(fields=['palmtec_id', 'expense_datetime'], name='expense_dat_palmtec_75bae3_idx'), models.Index(fields=['company_code', 'expense_date'], name='expense_dat_company_67bfcb_idx'), models.Index(fields=['company_code'], name='expense_dat_company_4a8245_idx'), models.Index(fields=['expense_date'], name='expense_dat_expense_4216d2_idx'), models.Index(fields=['unique_code'], name='expense_dat_unique__3098dc_idx'), models.Index(fields=['schedule_no', 'trip_no'], name='expense_dat_schedul_57f230_idx')],
                'constraints': [models.UniqueConstraint(fields=('palmtec_id', 'company_code', 'schedule_no', 'trip_no', 'expense_datetime'), name='uniq_device_company_expense')],
            },
        ),
    ]
