# Generated by Django 5.2.9 on 2026-05-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0052_add_expense_data'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expensedata',
            name='uniq_device_company_expense',
        ),
        migrations.RemoveConstraint(
            model_name='odometerdata',
            name='uniq_device_company_odometer',
        ),
        migrations.AlterField(
            model_name='expensedata',
            name='palmtec_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='odometerdata',
            name='palmtec_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='expensedata',
            constraint=models.UniqueConstraint(fields=('company_code', 'schedule_no', 'trip_no', 'expense_datetime', 'expense_type'), name='uniq_device_company_expense'),
        ),
        migrations.AddConstraint(
            model_name='odometerdata',
            constraint=models.UniqueConstraint(fields=('company_code', 'schedule_no', 'trip_no', 'start_datetime'), name='uniq_device_company_odometer'),
        ),
    ]
