# Generated by Django 5.2.9 on 2026-05-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0053_add_odometer_expense_dat_parsing'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensedata',
            name='expense_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rawdatalog',
            name='source',
            field=models.CharField(choices=[('transaction', 'Transaction'), ('trip_open', 'Trip Open'), ('trip_close', 'Trip Close'), ('trip_close_summary', 'Trip Close Summary'), ('schedule_open', 'Schedule Open'), ('schedule_close', 'Schedule Close'), ('schedule_close_summary', 'Schedule Close Summary')], max_length=25),
        ),
    ]
