# Generated by Django 5.2.9 on 2026-05-20 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0054_add_expense_name_to_expense_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiondata',
            old_name='total_record',
            new_name='passenger_count',
        ),
        migrations.RenameField(
            model_name='tripclosedata',
            old_name='total_record',
            new_name='total_passengers',
        ),
    ]
