# Generated by Django 5.2.9 on 2026-05-20 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0056_add_schedule_data_trip_data_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transactiondata',
            name='uniq_device_trip_ticket_datetime',
        ),
        migrations.RemoveField(
            model_name='transactiondata',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='transactiondata',
            name='trip_number',
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='schedule_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='TicketAppB.scheduledata'),
        ),
        migrations.AddConstraint(
            model_name='transactiondata',
            constraint=models.UniqueConstraint(fields=('palmtec_id', 'company_code', 'ticket_number', 'ticket_date', 'ticket_time'), name='uniq_device_ticket_datetime'),
        ),
    ]
