# Generated by Django 5.2.9 on 2026-05-20 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0057_update_transaction_data_remove_schedule_trip_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledata',
            old_name='auto_closed',
            new_name='auto_opened',
        ),
        migrations.RenameField(
            model_name='tripdata',
            old_name='auto_closed',
            new_name='auto_opened',
        ),
        migrations.AddField(
            model_name='scheduledata',
            name='bus_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_data', to='TicketAppB.vehicletype'),
        ),
        migrations.AddField(
            model_name='scheduledata',
            name='conductor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_schedule_data', to='TicketAppB.employee'),
        ),
        migrations.AddField(
            model_name='scheduledata',
            name='driver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_schedule_data', to='TicketAppB.employee'),
        ),
        migrations.AddField(
            model_name='tripdata',
            name='bus_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_data', to='TicketAppB.vehicletype'),
        ),
        migrations.AddField(
            model_name='tripdata',
            name='conductor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_trip_data', to='TicketAppB.employee'),
        ),
        migrations.AddField(
            model_name='tripdata',
            name='driver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_trip_data', to='TicketAppB.employee'),
        ),
    ]
