# Generated by Django 5.2.9 on 2026-05-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0058_rename_auto_closed_add_fk_fields_to_trip_schedule_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='address_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
