# Generated by Django 5.2.9 on 2026-05-21 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0060_add_is_active_to_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensedata',
            name='schedule_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_records', to='TicketAppB.scheduledata'),
        ),
        migrations.AddField(
            model_name='expensedata',
            name='trip_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_records', to='TicketAppB.tripdata'),
        ),
        migrations.AddField(
            model_name='odometerdata',
            name='schedule_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odometer_records', to='TicketAppB.scheduledata'),
        ),
        migrations.AddField(
            model_name='odometerdata',
            name='trip_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odometer_records', to='TicketAppB.tripdata'),
        ),
    ]
