# Generated by Django 5.2.9 on 2026-05-22 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0062_remove_scheduleopendata_company_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensedata',
            name='expense_master_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_records', to='TicketAppB.expensemaster'),
        ),
    ]
