# Generated by Django 5.2.9 on 2026-05-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0063_expensedata_expense_master_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondata',
            name='palmtec_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='ticket_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='ticket_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='ticket_time',
            field=models.TimeField(),
        ),
    ]
