memset(HttpDataBuff,0,512);
memset(cHttpDataBufer,0,sizeof(cHttpDataBufer));
sprintf(HttpDataBuff,"fn=TrpCl|%s|%s|%d|%d|%04d-%02d-%02d|%02d:%02d:00|"\
"%04d-%02d-%02d|%02d:%02d:00|"\
"%ld|%ld|%d|%d|%d|%d|%d|%d|%d|%d|"\
"%0.2f|%.02f|%.02f|%.02f|%.02f|%.02f|%.02f|"\
"%.02f|%.02f|%.02f|%d|%.02f|%s|%c|",
gSetup.PalmtecID,gLicenseInfo.cLicenseCode,gReport.cSchedule,gReport.cTripNo,gReport.cStartY+2000,gReport.cStartMO,gReport.cStartD,
gReport.cStartH,gReport.cStartM,
gReport.cEndY,gReport.cEndMO,gReport.cEndD,gReport.cEndH,gReport.cEndM,
gReport.lSTicketNo,gReport.lETicketNo,
gReport.sFull+gReport.uFull,gReport.sHalf+gReport.uChild,gReport.sST1+gReport.uSTCount,gReport.sLugg+gReport.uLugg,
gReport.sPhy+gReport.uPhy,gReport.sPass,gReport.sLadies+gReport.uLadies,gReport.sSenior+gReport.uSenior,
gReport.fFullColl+gReport.uFullColl,gReport.fHalfColl+gReport.uChildColl,gReport.fSTColl+gReport.uSTColl,
gReport.fLuggageColl+gReport.uLuggColl,gReport.fPhyColl+gReport.uPhyColl,gReport.fLadiColl+gReport.uLadiesColl,
gReport.fSeniorColl+gReport.uSeniorColl,
gReport.fAdjustColl,gReport.fExpenseAmount,gReport.fTotalColl,gReport.sUpiTicketCount,gReport.fUPITicketAmount,
gReport.cRouteCode,gReport.cUpDownTrip);